name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-custom-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Build Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip

      - name: Build Application Artifact
        run: |
          # Run your build script that creates the artifact (e.g., app_artifact.zip)
          ./build.sh
          # The artifact should be placed at /tmp/app_artifact.zip for Packer to use

      - name: Run Integration Tests
        run: ./run_integration_tests.sh

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
          unzip packer_1.8.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run Packer Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: packer build custom-image.pkr.hcl
