name: Packer Status Check

on: [pull_request]

jobs:
  packer-status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
          unzip packer_1.8.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run Packer Format Check
        run: packer fmt -check=true -diff=true .

      - name: Initialize Packer
        run: packer init .

      - name: Run Packer Validate
        run: packer validate custom-image.pkr.hcl
