name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application Artifacts
        env:
          PORT: ${{ secrets.PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        run: ./scripts/build.sh

      - name: List Artifacts Directory
        run: ls -la ./artifacts

      - name: Install Packer Plugins
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GCP_API_TOKEN }}
        run: packer init packer/custom-image.pkr.hcl

      - name: Run Packer Format Check
        run: packer fmt -check packer/custom-image.pkr.hcl

      - name: Run Packer Validate
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_SUBNET_ID: ${{ secrets.AWS_DEFAULT_SUBNET_ID }}
          AWS_DEMO_ACCOUNT_ID: ${{ secrets.AWS_DEMO_ACCOUNT_ID }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          PORT: ${{ secrets.PORT }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          packer validate \
            -var "aws_region=${AWS_REGION}" \
            -var "aws_default_subnet_id=${AWS_DEFAULT_SUBNET_ID}" \
            -var "AWS_DEMO_ACCOUNT_ID=${AWS_DEMO_ACCOUNT_ID}" \
            -var "MYSQL_DATABASE=${MYSQL_DATABASE}" \
            -var "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" \
            -var "DB_USER=${DB_USER}" \
            -var "PORT=${PORT}" \
            -var "DB_DIALECT=${DB_DIALECT}" \
            -var "DB_HOST=${DB_HOST}" \
            packer/custom-image.pkr.hcl
